#!/usr/bin/perl
use warnings;
use strict;

my $dir = "./samples";

my $queue = [
  { file => "$dir/2.8.raw", loops => 6*5, },
  { file => "$dir/2.7.raw", loops => 6*5, },
  { file => "$dir/2.6.raw", loops => 6*5, },
  { file => "$dir/2.5.raw", loops => 6*5, },
  { file => "$dir/2.4.raw", loops => 6*5, },
  { file => "$dir/2.3.raw", loops => 6*5, },
  { file => "$dir/2.2.raw", loops => 6*5, },
  { file => "$dir/2.1.raw", loops => 6*5, },
  { file => "$dir/2.0.raw", loops => 6*5, },
];

unless(fork) {

  pipe R,W;
  if (fork) {
    open STDOUT, ">&W";
    close R;
    foreach my $item (@$queue) {
      my $count = 0;
      while ($count++ < $item->{loops}) {
        open(my $fh,"<",$item->{file});
	while ( !eof($fh) ) {
	  read( $fh, my $data, 1024 );
	  print STDOUT $data;
	}
        close $fh;
      }
    }
    close STDOUT;
    close W;
  } else {
    open STDIN, "<&R";
    close W;
    exec qw(play -t raw -c 2 -r 44100 -b 16 -e signed-integer -);
  }
}

wait;

__END__

#!/bin/bash
#catl ~/sleep-noclip.raw | play -t raw -c 2 -r 44100 -b 16 -e signed-integer -


